### ISSUE TITLE
ds_config.json in pretrain_13b_megatron_ds.sh need to add msamp configuration?

### ISSUE THREAD

**Issue by genggui001** [Azure/MS-AMP-Examples#18]
{
  "train_micro_batch_size_per_gpu": $BS,
  "train_batch_size": $GLOBAL_BATCH_SIZE,
  "gradient_clipping": $CLIP_GRAD,
  "zero_optimization": {
    "stage": $ZERO_STAGE
  },
  "bf16": {
    "enabled": true
  },
  "steps_per_print": $LOG_INTERVAL
}

Do I need to add msamp configuration?
For example:
   "msamp": {
     "enabled": true,
     "opt_level": "O3",
   }

**Comment by wkcn** [comment]
Hi @genggui001 , thanks for your attention to our work!

It is not necessary to add the MS-AMP configuration.
The reason is that the optimizer is `LBAdamW` when passing the argument `--msamp` (https://github.com/Azure/MS-AMP-Examples/blob/main/gpt3/Megatron-DeepSpeed.patch#L279), and DeepSpeed will utilize `FP8DeepSpeedZeroOptimizer` (https://github.com/Azure/MS-AMP/blob/main/msamp/deepspeed/runtime/engine.py#L213).

**Comment by genggui001** [comment]
thanks
